/* =====================================================================
   data.js — Single source of truth for Adam Roastery (محمص آدم)
   Pricing model:
     unit: "kg"    -> sold by weight, weight selector 100g..1000g,
                      `price` is the price per 1 kg.
     unit: "piece" -> sold per unit, `price` is the fixed unit price.
   Taxonomy:
     cat  -> top-level category id (see CATEGORIES)
     sub  -> optional subcategory id (must exist in that category's `subs`)
   Each product carries a bilingual { ar, he } name and desc.
   Images live in assets/images/<category>/<file>.
   ===================================================================== */
(function () {
  "use strict";

  const STORE = {
    name: { ar: "محمص آدم", he: "פיצוחי אדם" },
    tagline: {
      ar: "أجود أنواع التمور والمكسرات الفاخرة",
      he: "מבחר התמרים והפיצוחים המשובחים ביותר"
    },
    whatsapp: "972523305309",            // wa.me number (no +)
    whatsappDisplay: "052-330-5309",
    location: "https://waze.com/ul/hsvc0gnwns",
    instagram: "https://www.instagram.com/mahmas_adam2?igsh=MXU4MGF2dmk1YW0ydA==",
    // 👉 The public URL the menu QR code points to. After deploying, set this to
    //    your live URL, then regenerate assets/images/qr-menu.svg with any free
    //    online QR generator (no build tools / Node required).
    menuUrl: "https://adam-premium-nuts.shop",
    developer: { name: "O&H Tech", url: "https://oh-tech.co" }
  };

  // Weight options in grams for kg-unit products
  const WEIGHTS = [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000];

  // Reusable subcategory definitions
  const SUB = {
    treeNuts : { id: "tree-nuts", name: { ar: "مكسرات", he: "אגוזים" } },
    seeds    : { id: "seeds", name: { ar: "بذور", he: "גרעינים" } },
    legumes  : { id: "legumes", name: { ar: "بقوليات", he: "קטניות" } },
    ground   : { id: "ground", name: { ar: "مطحون", he: "טחון" } },
    whole    : { id: "whole", name: { ar: "حبوب", he: "גרגרים" } },
    blends   : { id: "blends", name: { ar: "خلطات", he: "תערובות" } },
    medjool  : { id: "medjool", name: { ar: "مجدول", he: "מג'הול" } },
    soft     : { id: "soft", name: { ar: "طري", he: "רך" } },
    stuffed  : { id: "stuffed", name: { ar: "محشي", he: "ממולא" } },
    dates    : { id: "dates", name: { ar: "تمور", he: "תמרים" } },
  };
  const CATEGORIES = [
    { id: "coffee",        name: { ar: "قهوة آدم", he: "קפה אדם" }, img: "assets/images/coffee/coffee-1.jpeg" },
    { id: "nuts",          name: { ar: "مجندلات", he: "פיצוחים" }, img: "assets/images/nuts/nuts-13.jpeg" },
    { id: "natural-nuts",  name: { ar: "مكسرات طبيعية", he: "פיצוחים טבעיים" }, img: "assets/images/natural-nuts/natural-nuts-5.jpeg" },
    { id: "dried", name: { ar: "مجففات", he: "פירות יבשים" }, img: "assets/images/dried/dried-2.jpeg",
      subs: [SUB.dates, SUB.soft, SUB.stuffed] },
    { id: "espresso",      name: { ar: "إسبريسو", he: "אספרסו" }, img: "assets/images/espresso/espresso-9.jpeg" },
    { id: "specials",      name: { ar: "العروض", he: "מבצעים" }, img: "assets/images/specials/تنزيلات-מבצעים.jpg" },
    { id: "spices", name: { ar: "بهارات", he: "תבלינים" }, img: "assets/images/spices/spices-1.png",
      subs: [SUB.ground, SUB.whole, SUB.blends] },
    { id: "sweets",        name: { ar: "حلويات", he: "מתוקים" }, img: "assets/images/sweets/sweets-2.jpeg" },
    { id: "snacks",        name: { ar: "حلويات خفيفة", he: "חטיפים" }, img: "assets/images/snacks/snacks-4.jpeg" },
    { id: "gummy",         name: { ar: "حلوى جيلي", he: "סוכריות גומי" }, img: "assets/images/gummy/gummy-19.jpeg" },
  ];

  const im = (cat, file) => `assets/images/${cat}/${file}`;

  const PRODUCTS = [
    /* ---------------- NUTS (by weight) ---------------- */
    { id: "nuts-1", cat: "nuts", available: false, unit: "kg", price: 35, img: im("nuts","nuts-1.jpeg"),
      name: { ar: "بزر أسود مجندل", he: "גרעינים שחורים מלוחים" },
      desc: { ar: "بزر عبّاد الشمس الأسود المحمّص والمملّح، مقرمش ولذيذ للتسالي.", he: "גרעיני חמנייה שחורים קלויים ומלוחים, פריכים וטעימים לנשנוש." } },
    { id: "nuts-2", cat: "nuts", available: true, sub: "seeds", unit: "kg", price: 30, img: im("nuts","nuts-2.jpeg"),
      name: { ar: "بزر أسود غير مملح", he: "גרעינים שחורים ללא מלח" },
      desc: { ar: "بزر أسود محمّص بدون ملح، خيار صحي ومثالي للتسالي اليومية.", he: "גרעינים שחורים קלויים ללא מלח, בחירה בריאה לנשנוש יומיומי." } },
    { id: "nuts-3", cat: "nuts", available: true, sub: "seeds", unit: "kg", price: 50, img: im("nuts","nuts-3.jpeg"),
      name: { ar: "بزر بطيخ", he: "גרעיני אבטיח" },
      desc: { ar: "بزر البطيخ المحمّص بنكهته الغنية وقيمته الغذائية العالية.", he: "גרעיני אבטיח קלויים, טעם עשיר וערך תזונתי גבוה." } },
    { id: "nuts-4", cat: "nuts", available: true, sub: "seeds", unit: "kg", price: 45, img: im("nuts","nuts-4.jpeg"),
      name: { ar: "بزر قرع", he: "גרעיני דלעת" },
      desc: { ar: "بزر اليقطين المحمّص، غني بالبروتين ومثالي للوجبات الخفيفة.", he: "גרעיני דלעת קלויים, עשירים בחלבון ומושלמים לנשנוש." } },
    { id: "nuts-5", cat: "nuts", available: true, sub: "tree-nuts", unit: "kg", price: 35, img: im("nuts","nuts-5.jpeg"),
      name: { ar: "بندق أمريكي", he: "בוטן אמריקאי" },
      desc: { ar: "بندق أمريكي محمّص بقشره، نكهة كلاسيكية وقرمشة مميّزة.", he: "בוטן אמריקאי קלויים בקליפתם, טעם קלאסי ופריכות מיוחדת." } },
    { id: "nuts-6", cat: "nuts", available: true, sub: "tree-nuts", unit: "kg", price: 80, img: im("nuts","nuts-6.jpeg"),
      name: { ar: "بندق مملح", he: "אגוזי לוז מלוחים" },
      desc: { ar: "بندق محمّص ومملّح بعناية، غني بالنكهة ومثالي للضيافة.", he: "אגוזי לוז קלויים ומלוחים בקפידה, עשירים בטעם ומושלמים לאירוח." } },
    { id: "nuts-7", cat: "nuts", available: true, sub: "tree-nuts", unit: "kg", price: 80, img: im("nuts","nuts-7.jpeg"), bestseller: true,
      name: { ar: "جوز فاخر", he: "אגוזי מלך משובחים" },
      desc: { ar: "عين جوز كاملة فاخرة، طازجة ومقرمشة بطعم غني ومميّز.", he: "אגוזי מלך שלמים ומשובחים, טריים ופריכים בטעם עשיר." } },
    { id: "nuts-8", cat: "nuts", available: true, sub: "legumes", unit: "kg", price: 45, img: im("nuts","nuts-8.jpeg"),
      name: { ar: "حمص محمّص", he: "חומוס קלוי" },
      desc: { ar: "حمص محمّص ذهبي مقرمش، تسالي شعبية أصيلة ولذيذة.", he: "חומוס קלוי זהוב ופריך, נשנוש מסורתי אותנטי וטעים." } },
    { id: "nuts-9", cat: "nuts", available: true, sub: "legumes", unit: "kg", price: 50, img: im("nuts","nuts-9.jpeg"),
      name: { ar: "رفيولي", he: "רביולי" },
      desc: { ar: "رفيولي مقرمش بطبقة خارجية ذهبية ونكهة لا تُقاوم.", he: "רביולי פריך בציפוי זהוב וטעם שאי אפשר לעמוד בפניו." } },
    { id: "nuts-10", cat: "nuts", available: true, sub: "tree-nuts", unit: "kg", price: 70, img: im("nuts","nuts-10.jpeg"), bestseller: true,
      name: { ar: "فستق حلبي فاخر", he: "פיסטוק חלבי משובח" },
      desc: { ar: "فستق حلبي فاخر محمّص ومملّح، ملكة المكسرات بطعمها الغني.", he: "פיסטוק חלבי משובח, קלוי ומלוח — מלכת הפיצוחים בטעם עשיר." } },
    { id: "nuts-11", cat: "nuts", available: true, sub: "tree-nuts", unit: "kg", price: 45, img: im("nuts","nuts-11.jpeg"),
      name: { ar: "فستق عبّيدي", he: "בוטנים" },
      desc: { ar: "فستق عبّيدي محمّص بنكهته المميّزة وسعره الاقتصادي.", he: "פיסטוק עבידי קלוי בטעם מיוחד ובמחיר משתלם." } },
    { id: "nuts-12", cat: "nuts", available: true, sub: "tree-nuts", unit: "kg", price: 50, img: im("nuts","nuts-12.jpeg"),
      name: { ar: "كابوكيم", he: "קבוקים" },
      desc: { ar: "كابوكيم تركي محمّص بقشرة مقرمشة وطعم غني.", he: "קבוקים טורקי קלוי בקליפה פריכה וטעם עשיר." } },
    { id: "nuts-13", cat: "nuts", available: true, sub: "tree-nuts", unit: "kg", price: 70, img: im("nuts","nuts-13.jpeg"), bestseller: true,
      name: { ar: "كاجو محمّص فاخر", he: "קשיו קלוי משובח" },
      desc: { ar: "كاجو محمّص ذهبي بقوام كريمي ونكهة فاخرة.", he: "קשיו קלוי זהוב במרקם קרמי וטעם משובח." } },
    { id: "nuts-14", cat: "nuts", available: true, sub: "tree-nuts", unit: "kg", price: 70, img: im("nuts","nuts-14.jpeg"), bestseller: true,
      name: { ar: "لوز فاخر", he: "שקדים אמריקאים משובחים" },
      desc: { ar: "لوز أمريكي محمّص بحجمه الكبير وطعمه المقرمش الغني.", he: "שקדים אמריקאים קלויים, גדולים, פריכים וטעימים." } },
    { id: "nuts-15", cat: "nuts", available: true, sub: "tree-nuts", unit: "kg", price: 120, img: im("nuts","nuts-15.jpeg"),
      name: { ar: "مكاديميا محمّصة", he: "מקדמיה קלויה" },
      desc: { ar: "مكاديميا محمّصة فاخرة بقوام زبدي ونكهة استثنائية.", he: "מקדמיה קלויה משובחת במרקם חמאתי וטעם יוצא דופן." } },
    { id: "nuts-16", cat: "nuts", available: true, sub: "tree-nuts", unit: "kg", price: 80, img: im("nuts","nuts-16.jpeg"),
      name: { ar: "مكاديميا مع قشر", he: "מקדמיה עם קליפה" },
      desc: { ar: "مكاديميا بقشرها الطبيعي، طازجة وغنية بالنكهة.", he: "מקדמיה עם קליפתה הטבעית, טרייה ועשירה בטעם." } },
    { id: "adam-mix", cat: "nuts", available: true, sub: "blends", unit: "kg", price: 60, img: im("nuts","nuts-17.jpeg"), bestseller: true,
      name: { ar: "مخلوطة آدم", he: "תערובת אדם" },
      desc: { ar: "خلطة جاهزة مختارة من محمص آدم بمذاق متوازن ومناسب للضيافة.", he: "תערובת הבית של אדם בטעם מאוזן ומושלם לאירוח." } },
    { id: "custom-mix", cat: "nuts", available: true, sub: "blends", unit: "kg", price: 0, img: im("nuts","nuts-17.jpeg"), customMix: true,
      name: { ar: "اصنع مخلوطة خاصة", he: "הרכבת תערובת אישית" },
      desc: { ar: "اختر أنواع المكسرات والوزن لكل نوع، وسيتم حساب السعر تلقائياً حسب اختيارك.", he: "בחרו סוגי פיצוחים ומשקל לכל סוג, והמחיר יחושב אוטומטית." } },
    /* ---------------- NATURAL NUTS (by weight) ---------------- */
    { id: "nat-1", cat: "natural-nuts", available: true, unit: "kg", price: 45, img: im("natural-nuts","natural-nuts-1.jpeg"),
      name: { ar: "بزر قرع مقشّر", he: "גרעיני דלעת קלופים" },
      desc: { ar: "حب قرع مقشّر طبيعي، جاهز للأكل وغني بالعناصر الغذائية.", he: "גרעיני דלעת קלופים טבעיים, מוכנים לאכילה ועשירים בערכים." } },
    { id: "nat-2", cat: "natural-nuts", available: true, unit: "kg", price: 70, img: im("natural-nuts","natural-nuts-2.jpeg"),
      name: { ar: "جوز بيكان", he: "פקאן" },
      desc: { ar: "جوز بيكان طبيعي بنكهة حلوة ناعمة وقوام مقرمش.", he: "פקאן טבעי בטעם מתקתק עדין ומרקם פריך." } },
    { id: "nat-3", cat: "natural-nuts", available: true, unit: "kg", price: 120, img: im("natural-nuts","natural-nuts-3.jpeg"),
      name: { ar: "صنوبر", he: "צנובר" },
      desc: { ar: "صنوبر فاخر طبيعي، إضافة راقية للأطباق والحلويات.", he: "צנובר משובח טבעי, תוספת יוקרתית למנות ולקינוחים." } },
    { id: "nat-4", cat: "natural-nuts", available: true, unit: "kg", price: 40, img: im("natural-nuts","natural-nuts-4.jpeg"),
      name: { ar: "عين الشمس مقشّر", he: "גרעיני חמנייה קלופים" },
      desc: { ar: "لب عبّاد الشمس المقشّر، خفيف وصحي وسهل التناول.", he: "גרעיני חמנייה קלופים, קלים, בריאים ונוחים לאכילה." } },
    { id: "nat-5", cat: "natural-nuts", available: true, unit: "kg", price: 120, img: im("natural-nuts","natural-nuts-5.jpeg"),
      name: { ar: "فستق حلبي مقشّر", he: "פיסטוק חלבי קלוף" },
      desc: { ar: "حب فستق حلبي مقشّر بلونه الأخضر الزاهي ونكهته الفاخرة.", he: "פיסטוק חלבי קלוף בצבע ירוק עז ובטעם משובח." } },
    { id: "nat-6", cat: "natural-nuts", available: true, unit: "kg", price: 65, img: im("natural-nuts","natural-nuts-6.jpeg"),
      name: { ar: "كاجو مقشّر", he: "קשיו קלוף" },
      desc: { ar: "كاجو طبيعي مقشّر نيء، مثالي للطبخ والتزيين.", he: "קשיו טבעי קלוף, מושלם לבישול ולקישוט." } },
    { id: "nat-7", cat: "natural-nuts", available: true, unit: "kg", price: 60, img: im("natural-nuts","natural-nuts-7.jpeg"),
      name: { ar: "لوز طبيعي", he: "שקדים טבעיים" },
      desc: { ar: "لوز طبيعي نيء بقشرته البنية، صحي ومتعدد الاستخدامات.", he: "שקדים טבעיים עם קליפתם החומה, בריאים ורב-שימושיים." } },
    { id: "nat-8", cat: "natural-nuts", available: true, unit: "kg", price: 60, img: im("natural-nuts","natural-nuts-8.jpeg"),
      name: { ar: "لوز مقطّع أرباع", he: "שקדים חתוכים לרבעים" },
      desc: { ar: "لوز مقطّع أرباع جاهز للخَبز والطبخ والتزيين.", he: "שקדים חתוכים לרבעים, מוכנים לאפייה, בישול וקישוט." } },
    { id: "nat-9", cat: "natural-nuts", available: true, unit: "kg", price: 60, img: im("natural-nuts","natural-nuts-9.jpeg"),
      name: { ar: "لوز مقطّع أنصاف", he: "שקדים חצויים" },
      desc: { ar: "لوز مقطّع أنصاف مثالي للحلويات والمعجنات.", he: "שקדים חצויים, מושלמים לקינוחים ולמאפים." } },
    /* ---------------- DATES (by weight) ---------------- */
    { id: "date-1", cat: "dried", available: true, sub: "medjool", unit: "kg", price: 45, img: im("dried","dried-2.jpeg"), bestseller: true,
      name: { ar: "تمر مجدول فاخر", he: "תמר מג'הול משובח" },
      desc: { ar: "تمر مجدول فاخر طري وغني بالسكر الطبيعي، حبّات كبيرة ممتلئة.", he: "תמר מג'הול משובח, רך ועשיר בסוכר טבעי, פרי גדול ומלא." } },
    /* ---------------- DRIED FRUITS (by weight) ---------------- */
    { id: "dry-1", cat: "dried", available: true, unit: "kg", price: 50, img: im("dried","dried-1.jpeg"),
      name: { ar: "أناناس مجفّف", he: "אננס מיובש" },
      desc: { ar: "شرائح أناناس مجفّفة بنكهة استوائية حلوة ومنعشة.", he: "פרוסות אננס מיובש בטעם טרופי מתוק ומרענן." } },
    { id: "dry-3", cat: "dried", available: true, unit: "kg", price: 55, img: im("dried","dried-3.jpeg"),
      name: { ar: "زبيب", he: "צימוקים" },
      desc: { ar: "زبيب طبيعي حلو، مثالي للتسالي والخَبز والطبخ.", he: "צימוקים טבעיים ומתוקים, מושלמים לנשנוש, אפייה ובישול." } },
    { id: "dry-4", cat: "dried", available: true, unit: "kg", price: 60, img: im("dried","dried-4.jpeg"),
      name: { ar: "عين البقرة (خوخ)", he: "שזיפים מיובשים" },
      desc: { ar: "خوخ مجفّف طري بنكهة غنية وفوائد غذائية عالية.", he: "שזיפים מיובשים רכים בטעם עשיר ובערך תזונתי גבוה." } },
    { id: "dry-5", cat: "dried", available: true, unit: "kg", price: 65, img: im("dried","dried-5.jpeg"),
      name: { ar: "قطين (تين مجفّف)", he: "תאנים מיובשות" },
      desc: { ar: "تين مجفّف طبيعي حلو المذاق وغني بالألياف.", he: "תאנים מיובשות טבעיות, מתוקות ועשירות בסיבים." } },
    { id: "dry-6", cat: "dried", available: true, unit: "kg", price: 60, img: im("dried","dried-6.jpeg"),
      name: { ar: "مشمش مجفّف", he: "משמש מיובש" },
      desc: { ar: "مشمش مجفّف بلونه الذهبي ونكهته الحلوة الحامضة.", he: "משמש מיובש בצבע זהוב ובטעם מתוק-חמצמץ." } },
    { id: "dry-7", cat: "dried", available: true, unit: "kg", price: 45, img: im("dried","dried-7.jpg"),
      name: { ar: "التوت البري", he: "חמוציות" },
      desc: { ar: "توت بري مجفّف بنكهة حلوة حامضة، مناسب للتسالي والحلويات.", he: "חמוציות מיובשות בטעם מתוק-חמצמץ, מתאימות לנשנוש ולקינוחים." } },
    /* ---------------- SPICES (by weight) ---------------- */
    { id: "spc-1", cat: "spices", available: true, sub: "ground", unit: "kg", price: 100, img: im("spices","spices-1.png"),
      name: { ar: "بابريكا حارّة", he: "פפריקה חריפה" },
      desc: { ar: "بابريكا حمراء حارّة تضيف لوناً ونكهة ناريّة لأطباقك.", he: "פפריקה אדומה חריפה שמוסיפה צבע וטעם לוהט למנות." } },
    { id: "spc-2", cat: "spices", available: true, sub: "ground", unit: "kg", price: 100, img: im("spices","spices-2.png"),
      name: { ar: "بابريكا حلوة", he: "פפריקה מתוקה" },
      desc: { ar: "بابريكا حمراء حلوة بنكهة معتدلة ولون شهي.", he: "פפריקה אדומה מתוקה בטעם עדין ובצבע מפתה." } },
    { id: "spc-3", cat: "spices", available: true, sub: "ground", unit: "kg", price: 100, img: im("spices","spices-3.png"),
      name: { ar: "بابريكا مدخّنة", he: "פפריקה מעושנת" },
      desc: { ar: "بابريكا مدخّنة بنكهة عميقة تمنح الأطباق طابعاً مميّزاً.", he: "פפריקה מעושנת בטעם עמוק שמעניק למנות אופי מיוחד." } },
    { id: "spc-4", cat: "spices", available: true, sub: "whole", unit: "kg", price: 130, img: im("spices","spices-4.png"),
      name: { ar: "بهار أبو ريحة حب", he: "פלפל אנגלי גרגרים" },
      desc: { ar: "بهار أبو ريحة (البهار الحلو) حب كامل لنكهة عطرية دافئة.", he: "פלפל אנגלי גרגרים שלמים לטעם ארומטי וחמים." } },
    { id: "spc-5", cat: "spices", available: true, sub: "ground", unit: "kg", price: 130, img: im("spices","spices-5.jpeg"),
      name: { ar: "بهار أبو ريحة مطحون", he: "פלפל אנגלי טחון" },
      desc: { ar: "بهار أبو ريحة مطحون ناعم، عطري ومثالي للتتبيل.", he: "פלפל אנגלי טחון דק, ארומטי ומושלם לתיבול." } },
    { id: "spc-6", cat: "spices", available: true, sub: "blends", unit: "kg", price: 100, img: im("spices","spices-6.jpeg"),
      name: { ar: "بهار دجاج", he: "תבלין לעוף" },
      desc: { ar: "خلطة بهارات الدجاج المتوازنة لمذاق غني وشهي.", he: "תערובת תבלינים לעוף, מאוזנת לטעם עשיר ומשובח." } },
    { id: "spc-7", cat: "spices", available: true, sub: "blends", unit: "kg", price: 100, img: im("spices","spices-7.jpeg"),
      name: { ar: "بهار شاورما", he: "תבלין שווארמה" },
      desc: { ar: "خلطة بهارات الشاورما الأصيلة بنكهتها الشرقية المميّزة.", he: "תערובת תבליני שווארמה אותנטית בטעם מזרחי מובהק." } },
    { id: "spc-8", cat: "spices", available: true, sub: "blends", unit: "kg", price: 100, img: im("spices","spices-8.webp"),
      name: { ar: "بهار كاري", he: "קארי" },
      desc: { ar: "كاري أصفر عطري بخلطة توابل غنية ومتوازنة.", he: "קארי צהוב ארומטי בתערובת תבלינים עשירה ומאוזנת." } },
    { id: "spc-9", cat: "spices", available: true, sub: "blends", unit: "kg", price: 100, img: im("spices","spices-9.jpeg"),
      name: { ar: "بهار للطبخ", he: "תערובת תבלינים לבישול" },
      desc: { ar: "خلطة بهارات شاملة لجميع أنواع الطبخ اليومي.", he: "תערובת תבלינים כללית לכל סוגי הבישול היומיומי." } },
    { id: "spc-10", cat: "spices", available: true, sub: "blends", unit: "kg", price: 100, img: im("spices","spices-10.jpeg"),
      name: { ar: "بهار مقلوبة", he: "תבלין למקלובה" },
      desc: { ar: "خلطة بهارات المقلوبة لنكهة شرقية أصيلة لا تُنسى.", he: "תערובת תבלינים למקלובה לטעם מזרחי אותנטי ובלתי נשכח." } },
    { id: "spc-11", cat: "spices", available: true, sub: "ground", unit: "kg", price: 100, img: im("spices","spices-11.jpeg"),
      name: { ar: "تشيلي حارّ", he: "צ'ילי חריף" },
      desc: { ar: "فلفل تشيلي حارّ مطحون يضيف حرارة ونكهة قويّة.", he: "צ'ילי חריף טחון שמוסיף חריפות וטעם עוצמתי." } },
    { id: "spc-12", cat: "spices", available: true, sub: "ground", unit: "kg", price: 130, img: im("spices","spices-12.jpeg"),
      name: { ar: "جوز الطيب مطحون", he: "אגוז מוסקט טחון" },
      desc: { ar: "جوز الطيب المطحون بنكهته الدافئة المثالية للحلويات.", he: "אגוז מוסקט טחון בטעם חמים, מושלם לקינוחים." } },
    { id: "spc-13", cat: "spices", available: true, sub: "ground", unit: "kg", price: 100, img: im("spices","spices-13.jpeg"),
      name: { ar: "زنجبيل مطحون", he: "ג'ינג'ר טחון" },
      desc: { ar: "زنجبيل مطحون بنكهة حارّة منعشة للطبخ والمشروبات.", he: "ג'ינג'ר טחון בטעם חריף ומרענן לבישול ולמשקאות." } },
    { id: "spc-14", cat: "spices", available: true, sub: "ground", unit: "kg", price: 100, img: im("spices","spices-14.jpeg"),
      name: { ar: "سمّاق", he: "סומק" },
      desc: { ar: "سمّاق أحمر بنكهة حامضة منعشة، أساسي للمسخّن والسلطات.", he: "סומק אדום בטעם חמצמץ מרענן, חיוני למוסחן ולסלטים." } },
    { id: "spc-15", cat: "spices", available: true, sub: "whole", unit: "kg", price: 100, img: im("spices","spices-15.jpeg"),
      name: { ar: "فلفل أسود حب", he: "פלפל שחור גרגרים" },
      desc: { ar: "فلفل أسود حب كامل لنكهة طازجة عند الطحن.", he: "פלפל שחור גרגרים שלמים לטעם טרי בעת הטחינה." } },
    { id: "spc-16", cat: "spices", available: true, sub: "ground", unit: "kg", price: 100, img: im("spices","spices-16.jpeg"),
      name: { ar: "فلفل أسود خشن", he: "פלפל שחור גס" },
      desc: { ar: "فلفل أسود مجروش خشن لنكهة قويّة وملمس مميّز.", he: "פלפל שחור גרוס גס לטעם עז ולמרקם מיוחד." } },
    { id: "spc-17", cat: "spices", available: true, sub: "ground", unit: "kg", price: 100, img: im("spices","spices-17.jpeg"),
      name: { ar: "فلفل أسود مطحون", he: "פלפל שחור טחון" },
      desc: { ar: "فلفل أسود مطحون ناعم، أساسي في كل مطبخ.", he: "פלפל שחור טחון דק, בסיסי בכל מטבח." } },
    { id: "spc-18", cat: "spices", available: true, sub: "whole", unit: "kg", price: 100, img: im("spices","spices-18.jpeg"),
      name: { ar: "فلفل حب ألوان", he: "פלפל צבעוני גרגרים" },
      desc: { ar: "خليط فلفل ملوّن بحبّاته الكاملة لنكهة ومظهر مميّز.", he: "תערובת פלפל צבעוני בגרגרים שלמים לטעם ומראה מיוחד." } },
    { id: "spc-19", cat: "spices", available: true, sub: "whole", unit: "kg", price: 100, img: im("spices","spices-19.webp"),
      name: { ar: "قرفة عيدان", he: "קינמון מקלות" },
      desc: { ar: "أعواد قرفة طبيعية عطرية للمشروبات والطبخ.", he: "מקלות קינמון טבעיים וארומטיים למשקאות ולבישול." } },
    { id: "spc-20", cat: "spices", available: true, sub: "ground", unit: "kg", price: 100, img: im("spices","spices-20.jpeg"),
      name: { ar: "قرفة مطحونة", he: "קינמון טחון" },
      desc: { ar: "قرفة مطحونة ناعمة بنكهتها الدافئة الحلوة.", he: "קינמון טחון דק בטעם חמים ומתוק." } },
    { id: "spc-21", cat: "spices", available: true, sub: "whole", unit: "kg", price: 130, img: im("spices","spices-21.webp"),
      name: { ar: "قرنفل حب", he: "ציפורן שלם" },
      desc: { ar: "قرنفل حب كامل عطري للطبخ والمشروبات الساخنة.", he: "ציפורן שלם וארומטי לבישול ולמשקאות חמים." } },
    { id: "spc-22", cat: "spices", available: true, sub: "ground", unit: "kg", price: 130, img: im("spices","spices-22.jpeg"),
      name: { ar: "قرنفل مطحون", he: "ציפורן טחון" },
      desc: { ar: "قرنفل مطحون بنكهة قويّة عطرية مثالية للحلويات.", he: "ציפורן טחון בטעם עז וארומטי, מושלם לקינוחים." } },
    { id: "spc-23", cat: "spices", available: true, sub: "ground", unit: "kg", price: 100, img: im("spices","spices-23.webp"),
      name: { ar: "كركم مطحون", he: "כורכום טחון" },
      desc: { ar: "كركم مطحون بلونه الذهبي وفوائده الصحية العديدة.", he: "כורכום טחון בצבע זהוב ובסגולות בריאות רבות." } },
    { id: "spc-24", cat: "spices", available: true, sub: "ground", unit: "kg", price: 100, img: im("spices","spices-24.jpeg"),
      name: { ar: "كزبرة مطحونة", he: "כוסברה טחונה" },
      desc: { ar: "كزبرة مطحونة بنكهة حمضية منعشة للطبخ والتتبيل.", he: "כוסברה טחונה בטעם הדרי מרענן לבישול ולתיבול." } },
    { id: "spc-25", cat: "spices", available: true, sub: "whole", unit: "kg", price: 100, img: im("spices","spices-25.jpeg"),
      name: { ar: "ملح الهيمالايا", he: "מלח הימלאיה" },
      desc: { ar: "ملح هيمالايا وردي طبيعي غني بالمعادن.", he: "מלח הימלאיה ורוד טבעי, עשיר במינרלים." } },
    { id: "spc-26", cat: "spices", available: true, sub: "ground", unit: "kg", price: 50, img: im("spices","spices-26.png"),
      name: { ar: "ملح ليمون", he: "מלח לימון" },
      desc: { ar: "ملح ليمون (حامض الستريك) لإضافة حموضة منعشة.", he: "מלח לימון (חומצה ציטרית) להוספת חמיצות מרעננת." } },
    { id: "spc-27", cat: "spices", available: true, sub: "whole", unit: "kg", price: 70, img: im("spices","spices-27.png"),
      name: { ar: "ورق غار", he: "עלי דפנה" },
      desc: { ar: "ورق غار عطري يمنح الأطباق نكهة عميقة مميّزة.", he: "עלי דפנה ארומטיים שמעניקים למנות טעם עמוק ומיוחד." } },
    /* ---------------- COFFEE (fixed packages) ---------------- */
    { id: "cof-1", cat: "coffee", available: true, unit: "piece", price: 75, fixedWeight: { ar: "1 كيلو", he: "1 ק\"ג" }, img: im("coffee","coffee-1.jpeg"), bestseller: true,
      name: { ar: "قهوة آدم العربية 1 كيلو", he: "קפה אדם ערבי 1 ק\"ג" },
      desc: { ar: "عبوة كيلو من قهوة آدم العربية المحمّصة بخلطة الهيل الفاخرة.", he: "אריזת קילוגרם של קפה אדם ערבי קלוי בתערובת הל משובחת." } },
    { id: "cof-2", cat: "coffee", available: true, unit: "piece", price: 38, fixedWeight: { ar: "نصف كيلو", he: "חצי ק\"ג" }, img: im("coffee","coffee-1.jpeg"),
      name: { ar: "قهوة آدم العربية نصف كيلو", he: "קפה אדם ערבי חצי ק\"ג" },
      desc: { ar: "عبوة نصف كيلو من قهوة آدم العربية المحمّصة بخلطة الهيل الفاخرة.", he: "אריזת חצי קילוגרם של קפה אדם ערבי קלוי בתערובת הל משובחת." } },
    /* ---------------- ESPRESSO (per piece) ---------------- */
    { id: "esp-1", cat: "espresso", available: true, unit: "piece", price: 18, img: im("espresso","espresso-1.png"),
      name: { ar: "كبسولات بلاك لماكينة كلوب", he: "קפסולות בלאק למכונת קלאב" },
      desc: { ar: "كبسولات إسبريسو قويّة لماكينة كلوب بنكهة غنية.", he: "קפסולות אספרסו עוצמתי למכונת קלאב בטעם עשיר." } },
    { id: "esp-2", cat: "espresso", available: true, unit: "piece", price: 18, img: im("espresso","espresso-2.png"),
      name: { ar: "كبسولات ديليتسيوسو", he: "קפסולות דליציוסו" },
      desc: { ar: "كبسولات إسبريسو ناعمة متوازنة لماكينة كلوب.", he: "קפסולות אספרסו עדין ומאוזן למכונת קלאב." } },
    { id: "esp-3", cat: "espresso", available: true, unit: "piece", price: 50, img: im("espresso","espresso-3.jpeg"),
      name: { ar: "لافازا إنتينسو", he: "לוואצה אינטנסו" },
      desc: { ar: "كبسولات لافازا إنتينسو بنكهة مكثّفة وكريما غنية.", he: "קפסולות לוואצה אינטנסו בטעם מרוכז וקרמה עשירה." } },
    { id: "esp-4", cat: "espresso", available: true, unit: "piece", price: "", img: im("espresso","espresso-4.jpeg"),
      name: { ar: "منتج إسبريسو 4", he: "מוצר אספרסו 4" },
      desc: { ar: "منتج إسبريسو متوفر في المحمص.", he: "מוצר אספרסו זמין במטחנה." } },
    { id: "esp-5", cat: "espresso", available: true, unit: "piece", price: 90, img: im("espresso","espresso-5.jpeg"),
      name: { ar: "لافازا فورتي", he: "לוואצה פורטה" },
      desc: { ar: "كبسولات لافازا فورتي القويّة لعشّاق القهوة المركّزة.", he: "קפסולות לוואצה פורטה עוצמתיות לחובבי קפה מרוכז." } },
    { id: "esp-6", cat: "espresso", available: true, unit: "piece", price: 90, img: im("espresso","espresso-6.jpeg"),
      name: { ar: "لافازا بيانو", he: "לוואצה פיאנו" },
      desc: { ar: "كبسولات لافازا بيانو الناعمة بنكهة لطيفة ومتوازنة.", he: "קפסולות לוואצה פיאנו עדינות בטעם נעים ומאוזן." } },
    { id: "esp-7", cat: "espresso", available: true, unit: "piece", price: 50, img: im("espresso","espresso-7.png"),
      name: { ar: "لافازا كريما", he: "לוואצה קרמה" },
      desc: { ar: "كبسولات لافازا كريما بطبقة كريما غنية وكثيفة.", he: "קפסולות לוואצה קרמה עם שכבת קרמה עשירה." } },
    { id: "esp-8", cat: "espresso", available: true, unit: "piece", price: 300, img: im("espresso","espresso-8.jpeg"),
      name: { ar: "ماكينة قهوة Omor", he: "מכונת קפה Omor" },
      desc: { ar: "ماكينة قهوة Omor عملية وأنيقة لإسبريسو منزلي مثالي.", he: "מכונת קפה Omor מעשית ואלגנטית לאספרסו ביתי מושלם." } },
    { id: "esp-9", cat: "espresso", available: true, unit: "piece", price: 400, img: im("espresso","espresso-9.jpeg"),
      name: { ar: "ماكينة قهوة لافازا", he: "מכונת קפה לוואצה" },
      desc: { ar: "ماكينة قهوة لافازا احترافية لإسبريسو بجودة المقاهي.", he: "מכונת קפה לוואצה מקצועית לאספרסו באיכות בתי קפה." } },
    { id: "esp-10", cat: "espresso", available: true, unit: "piece", price: 380, img: im("espresso","espresso-10.png"),
      name: { ar: "ماكينة قهوة كلوب", he: "מכונת קפה קלאב" },
      desc: { ar: "ماكينة قهوة كلوب متعدّدة الكبسولات بتصميم عصري.", he: "מכונת קפה קלאב רב-קפסולות בעיצוב מודרני." } },
    { id: "esp-11", cat: "espresso", available: true, unit: "piece", price: 18, img: im("espresso","espresso-11.png"),
      name: { ar: "كبسولات باسو", he: "קפסולות פאסו" },
      desc: { ar: "كبسولات باسو إسبريسو لماكينة كلوب بنكهة متوازنة.", he: "קפסולות פאסו אספרסו למכונת קלאב בטעם מאוזן." } },
    { id: "esp-12", cat: "espresso", available: true, unit: "piece", price: 18, img: im("espresso","espresso-12.jpeg"),
      name: { ar: "كبسولات كابتشينو", he: "קפסולות קפוצ'ינו" },
      desc: { ar: "كبسولات كابتشينو كريمية لماكينة كلوب بمذاق غني.", he: "קפסולות קפוצ'ינו קרמיות למכונת קלאב בטעם עשיר." } },
    { id: "esp-13", cat: "espresso", available: true, unit: "piece", price: 18, img: im("espresso","espresso-13.png"),
      name: { ar: "كبسولات كريم", he: "קפסולות קרם" },
      desc: { ar: "كبسولات كريم لماكينة كلوب بقوام ناعم ونكهة متوازنة.", he: "קפסולות קרם למכונת קלאב במרקם עדין וטעם מאוזן." } },
    { id: "esp-14", cat: "espresso", available: true, unit: "piece", price: 80, img: im("espresso","espresso-14.png"),
      name: { ar: "قهوة سيجافريدو", he: "קפה סגפרדו" },
      desc: { ar: "قهوة سيجافريدو الإيطالية الفاخرة بنكهتها العريقة.", he: "קפה סגפרדו האיטלקי המשובח בטעמו המסורתי." } },
    { id: "esp-15", cat: "espresso", available: true, unit: "piece", price: 50, img: im("espresso","espresso-15.jpeg"),
      name: { ar: "كبسولات S", he: "קפסולות S" },
      desc: { ar: "كبسولات إسبريسو متوافقة بنكهة غنية واقتصادية.", he: "קפסולות אספרסו תואמות בטעם עשיר ובמחיר משתלם." } },
    { id: "esp-16", cat: "espresso", available: true, unit: "piece", price: 20, img: im("espresso","espresso-16.jpg"),
      name: { ar: "كبسولات دولتشي جوستو", he: "קפסולות דולצ'ה גוסטו" },
      desc: { ar: "كبسولات دولتشي جوستو متنوّعة لمشروبات قهوة متعدّدة.", he: "קפסולות דולצ'ה גוסטו מגוונות למשקאות קפה שונים." } },
    { id: "esp-17", cat: "espresso", available: true, unit: "piece", price: "", img: im("espresso","espresso-17.jpg"),
      name: { ar: "منتج إسبريسو 17", he: "מוצר אספרסו 17" },
      desc: { ar: "منتج إسبريسو متوفر في المحمص.", he: "מוצר אספרסו זמין במטחנה." } },
    { id: "esp-18", cat: "espresso", available: true, unit: "piece", price: "", img: im("espresso","espresso-18.jpg"),
      name: { ar: "منتج إسبريسو 18", he: "מוצר אספרסו 18" },
      desc: { ar: "منتج إسبريسو متوفر في المحمص.", he: "מוצר אספרסו זמין במטחנה." } },
    { id: "esp-19", cat: "espresso", available: true, unit: "piece", price: "", img: im("espresso","espresso-19.jpg"),
      name: { ar: "منتج إسبريسو 19", he: "מוצר אספרסו 19" },
      desc: { ar: "منتج إسبريسو متوفر في المحمص.", he: "מוצר אספרסו זמין במטחנה." } },
    { id: "esp-20", cat: "espresso", available: true, unit: "piece", price: 18, img: im("espresso","espresso-20.png"),
      name: { ar: "كبسولات نسبريسو", he: "קפסולות נספרסו" },
      desc: { ar: "كبسولات متوافقة مع نسبريسو بنكهة إسبريسو غنية.", he: "קפסולות תואמות נספרסו בטעם אספרסו עשיר." } },
    { id: "esp-21", cat: "espresso", available: true, unit: "piece", price: "", img: im("espresso","espresso-21.png"),
      name: { ar: "منتج إسبريسو 21", he: "מוצר אספרסו 21" },
      desc: { ar: "منتج إسبريسو متوفر في المحمص.", he: "מוצר אספרסו זמין במטחנה." } },
    { id: "esp-22", cat: "espresso", available: true, unit: "piece", price: "", img: im("espresso","espresso-22.jpeg"),
      name: { ar: "منتج إسبريسو 22", he: "מוצר אספרסו 22" },
      desc: { ar: "منتج إسبريسو متوفر في المحمص.", he: "מוצר אספרסו זמין במטחנה." } },
    { id: "esp-23", cat: "espresso", available: true, unit: "piece", price: 18, img: im("espresso","espresso-23.jpeg"),
      name: { ar: "كبسولات شوكولاتة لماكينة كلوب", he: "קפסולות שוקולד למכונת קלאב" },
      desc: { ar: "كبسولات مشروب الشوكولاتة الساخنة لماكينة كلوب.", he: "קפסולות שוקו חם למכונת קלאב." } },
    { id: "esp-24", cat: "espresso", available: true, unit: "piece", price: 120, img: im("espresso","espresso-24.jpeg"),
      name: { ar: "سوبر كريما", he: "סופר קרמה" },
      desc: { ar: "خليط سوبر كريما لإسبريسو بطبقة كريما كثيفة ومثالية.", he: "תערובת סופר קרמה לאספרסו עם שכבת קרמה עשירה." } },
    /* ---------------- SPECIALS ---------------- */
    { id: "offer-espresso-6", cat: "specials", available: true, unit: "piece", price: 100, img: im("espresso","عرض 6=100.jpg"), offerBundle: "espresso-club-6",
      name: { ar: "عرض كبسولات إسبريسو كلوب 6 بـ 100", he: "מבצע קפסולות אספרסו קלאב 6 ב-100" },
      desc: { ar: "اختر أي 6 أنواع من كبسولات Espresso Club واحصل عليها بـ 100 شيكل.", he: "בחרו כל 6 סוגי קפסולות Espresso Club וקבלו אותן ב-100 ₪." } },
    /* ---------------- SWEETS (per piece / package) ---------------- */
    { id: "swt-1", cat: "sweets", available: true, unit: "piece", price: 70, img: im("sweets","sweets-1.jpeg"),
      name: { ar: "برازق حبيبة 700غ", he: "בראזק חביבה 700 גרם" },
      desc: { ar: "برازق حبيبة بالسمسم والفستق، حلوى شامية مقرمشة فاخرة.", he: "בראזק חביבה עם שומשום ופיסטוק, מתוק שאמי פריך ומשובח." } },
    { id: "swt-2", cat: "sweets", available: true, unit: "piece", price: 150, img: im("sweets","sweets-2.jpeg"), bestseller: true,
      name: { ar: "حلو شرقي النجمة 1 كغ", he: "מתוק מזרחי כוכב 1 ק\"ג" },
      desc: { ar: "تشكيلة حلويات شرقية فاخرة على شكل نجمة لأرقى المناسبات.", he: "מגוון מתוקים מזרחיים משובחים בצורת כוכב לאירועים מיוחדים." } },
    { id: "swt-3", cat: "sweets", available: true, unit: "piece", price: 100, img: im("sweets","sweets-3.jpeg"),
      name: { ar: "حلو شرقي 550غ", he: "מתוק מזרחי 550 גרם" },
      desc: { ar: "تشكيلة حلويات شرقية متنوّعة بحجم عائلي مناسب.", he: "מגוון מתוקים מזרחיים בגודל משפחתי נוח." } },
    { id: "swt-4", cat: "sweets", available: true, unit: "piece", price: 150, img: im("sweets","sweets-4.jpeg"),
      name: { ar: "حلو شرقي حبيبة 750غ", he: "מתוק מזרחי חביבה 750 גרם" },
      desc: { ar: "تشكيلة حلويات حبيبة الشرقية الفاخرة بأنواع متعدّدة.", he: "מגוון מתוקי חביבה מזרחיים משובחים בסוגים שונים." } },
    { id: "swt-5", cat: "sweets", available: true, unit: "piece", price: 70, img: im("sweets","sweets-5.jpeg"),
      name: { ar: "غريبة", he: "עוגיות ע'ריבה" },
      desc: { ar: "غريبة هشّة تذوب في الفم بنكهة السمن الأصيلة.", he: "ע'ריבה פריכה שנמסה בפה בטעם חמאה אותנטי." } },
    { id: "swt-6", cat: "sweets", available: true, unit: "piece", price: 110, img: im("sweets","sweets-6.jpeg"),
      name: { ar: "مشكّل برازق وغريبة ومعمول", he: "מארז בראזק, ע'ריבה ומעמול" },
      desc: { ar: "تشكيلة مشكّلة من البرازق والغريبة والمعمول الفاخر.", he: "מארז משולב של בראזק, ע'ריבה ומעמול משובח." } },
    { id: "swt-7", cat: "sweets", available: true, unit: "piece", price: 70, img: im("sweets","sweets-7.jpeg"),
      name: { ar: "مشكّل غريبة وبرازق", he: "מארז ע'ריבה ובראזק" },
      desc: { ar: "تشكيلة من الغريبة والبرازق بمذاق شامي أصيل.", he: "מארז ע'ריבה ובראזק בטעם שאמי אותנטי." } },
    { id: "swt-8", cat: "sweets", available: true, unit: "piece", price: 110, img: im("sweets","sweets-8.jpeg"),
      name: { ar: "مشكّل معمول", he: "מארז מעמול" },
      desc: { ar: "معمول محشي بالتمر والجوز والفستق، حلوى العيد الأصيلة.", he: "מעמול במילוי תמרים, אגוזים ופיסטוק, ממתק החג האותנטי." } },
    /* ---------------- SNACKS (by weight) ---------------- */
    { id: "snk-1", cat: "snacks", available: true, unit: "kg", price: 45, img: im("snacks","snacks-1.jpeg"),
      name: { ar: "بندقية", he: "בונדוקייה" },
      desc: { ar: "حلوى البندقية المقرمشة بالسمسم والمكسرات، تسالي تقليدية.", he: "ממתק בונדוקייה פריך עם שומשום ואגוזים, נשנוש מסורתי." } },
    { id: "snk-2", cat: "snacks", available: true, unit: "kg", price: 45, img: im("snacks","snacks-2.jpeg"),
      name: { ar: "جوز الهند", he: "ממתק קוקוס" },
      desc: { ar: "حلوى جوز الهند بنكهتها الاستوائية الحلوة والمميّزة.", he: "ממתק קוקוס בטעם טרופי מתוק ומיוחד." } },
    { id: "snk-3", cat: "snacks", available: true, unit: "kg", price: 45, img: im("snacks","snacks-3.jpeg"),
      name: { ar: "سكاكر ألوان", he: "סוכריות צבעוניות" },
      desc: { ar: "سكاكر ملوّنة متنوّعة تسعد الكبار والصغار.", he: "סוכריות צבעוניות מגוונות לשמחת קטנים וגדולים." } },
    { id: "snk-4", cat: "snacks", available: true, unit: "kg", price: 45, img: im("snacks","snacks-4.jpeg"),
      name: { ar: "سمسمية", he: "סומסומיה" },
      desc: { ar: "سمسمية بالسمسم والعسل، حلوى طاقة تقليدية لذيذة.", he: "סומסומיה עם שומשום ודבש, ממתק אנרגיה מסורתי וטעים." } },
    { id: "snk-5", cat: "snacks", available: true, unit: "kg", price: 45, img: im("snacks","snacks-5.jpeg"),
      name: { ar: "عين الشمس", he: "חטיף עין השמש" },
      desc: { ar: "حلوى عين الشمس بالبزر، مقرمشة وغنية بالطاقة.", he: "חטיף עין השמש עם גרעינים, פריך ועשיר באנרגיה." } },
    /* ---------------- GUMMY (by weight) ---------------- */
    { id: "gum-1", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-1.jpeg"),
      name: { ar: "جيلي توت", he: "גומי תות" },
      desc: { ar: "جيلي توت بنكهات فواكه حلوة.", he: "גומי תות בטעמי פירות מתוקים." } },
    { id: "gum-2", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-2.jpeg"),
      name: { ar: "جيلي عنب", he: "גומי ענבים" },
      desc: { ar: "جيلي عنب بنكهة فواكه منعشة.", he: "גומי ענבים בטעם פירות מרענן." } },
    { id: "gum-3", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-3.jpeg"),
      name: { ar: "جيلي فواكه", he: "גומי פירות" },
      desc: { ar: "جيلي فواكه متنوع بألوان ونكهات مختلفة.", he: "גומי פירות מגוון בצבעים וטעמים שונים." } },
    { id: "gum-4", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-4.jpeg"),
      name: { ar: "جيلي حيتان", he: "גומי לווייתנים" },
      desc: { ar: "جيلي على شكل حيتان بنكهات فواكه.", he: "גומי בצורת לווייתנים בטעמי פירות." } },
    { id: "gum-5", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-5.jpeg"),
      name: { ar: "جيلي مشكل", he: "גומי מעורב" },
      desc: { ar: "جيلي مشكل بأشكال وألوان متعددة.", he: "גומי מעורב בצורות וצבעים שונים." } },
    { id: "gum-6", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-6.jpeg"),
      name: { ar: "جيلي توت مملح", he: "גומי תות מלוח" },
      desc: { ar: "جيلي توت مملح بطعم مميز.", he: "גומי תות מלוח בטעם מיוחד." } },
    { id: "gum-7", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-7.jpeg"),
      name: { ar: "جيلي قلب أزرق", he: "גומי לב כחול" },
      desc: { ar: "جيلي على شكل قلب أزرق بنكهات فواكه.", he: "גומי בצורת לב כחול בטעמי פירות." } },
    { id: "gum-8", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-8.jpeg"),
      name: { ar: "جيلي عظم", he: "גומי עצם" },
      desc: { ar: "جيلي على شكل عظم بطعم حلو.", he: "גומי בצורת עצם בטעם מתוק." } },
    { id: "gum-9", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-9.jpeg"),
      name: { ar: "جيلي نجمة", he: "גומי כוכב" },
      desc: { ar: "جيلي على شكل نجمة بألوان جميلة.", he: "גומי בצורת כוכב בצבעים יפים." } },
    { id: "gum-10", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-10.jpeg"),
      name: { ar: "جيلي بيتزا", he: "גומי פיצה" },
      desc: { ar: "جيلي على شكل بيتزا بطعم فواكه.", he: "גומי בצורת פיצה בטעמי פירות." } },
    { id: "gum-11", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-11.jpeg"),
      name: { ar: "جيلي كرز", he: "גומי דובדבן" },
      desc: { ar: "جيلي كرز بطعم فاكهي غني.", he: "גומי דובדבן בטעם פירות עשיר." } },
    { id: "gum-12", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-12.jpeg"),
      name: { ar: "جيلي بطيخ", he: "גומי אבטיח" },
      desc: { ar: "جيلي بطيخ بطعم منعش.", he: "גומי אבטיח בטעם מרענן." } },
    { id: "gum-13", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-13.jpeg"),
      name: { ar: "جيلي كولا مملح", he: "גומי קולה מלוח" },
      desc: { ar: "جيلي كولا مملح بطعم مميز.", he: "גומי קולה מלוח בטעם מיוחד." } },
    { id: "gum-14", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-14.jpeg"),
      name: { ar: "جيلي بيض", he: "גומי ביצים" },
      desc: { ar: "جيلي على شكل بيض بطعم حلو.", he: "גומי בצורת ביצים בטעם מתוק." } },
    { id: "gum-15", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-15.jpeg"),
      name: { ar: "جيلي دببة", he: "גומי דובונים" },
      desc: { ar: "جيلي دببة كلاسيكي بنكهات فواكه.", he: "גומי דובונים קלאסי בטעמי פירות." } },
    { id: "gum-16", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-16.jpeg"),
      name: { ar: "جيلي موز", he: "גומי בננה" },
      desc: { ar: "جيلي موز بطعم حلو ومميز.", he: "גומי בננה בטעם מתוק ומיוחד." } },
    { id: "gum-17", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-17.jpeg"),
      name: { ar: "جيلي حيتان", he: "גומי לווייתנים" },
      desc: { ar: "جيلي حيتان ملون بنكهات فواكه.", he: "גומי לווייתנים צבעוני בטעמי פירות." } },
    { id: "gum-18", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-18.jpeg"),
      name: { ar: "جيلي ديدان ملون", he: "גומי תולעים צבעוני" },
      desc: { ar: "جيلي ديدان ملون بنكهات فواكه.", he: "גומי תולעים צבעוני בטעמי פירות." } },
    { id: "gum-19", cat: "gummy", available: true, unit: "kg", price: 45, img: im("gummy","gummy-19.jpeg"),
      name: { ar: "جيلي كولا", he: "גומי קולה" },
      desc: { ar: "جيلي كولا بطعم كلاسيكي.", he: "גומי קולה בטעם קלאסי." } },
  ];

  // Delivery rules — fee in shekels keyed by normalized city/village.
  const DELIVERY = {
    near: { fee: 10, places: ["مقيبلة", "מוקייבלה", "muqeible", "مقيبله", "صندلة", "סנדלה", "sandala", "صندله"] },
    geoAreas: [
      { id: "sandala", bounds: { south: 32.5198754, north: 32.5252186, west: 35.3207281, east: 35.3260335 } },
      { id: "muqeible", bounds: { south: 32.5106194, north: 32.5170321, west: 35.2865159, east: 35.3030750 } }
    ],
    far: { fee: 30 },
    pickup: { fee: 0 }
  };

  const PROMOS = [
    {
      id: "espresso-club-6",
      ids: ["esp-1", "esp-2", "esp-11", "esp-12", "esp-13", "esp-23"],
      qty: 6,
      unitPrice: 18,
      bundlePrice: 100
    }
  ];

  window.AdamData = { STORE, WEIGHTS, CATEGORIES, PRODUCTS, DELIVERY, PROMOS };
})();
